# Site settings
email: ktagilbert@gmail.com
baseurl: "/" # the subpath of your site, e.g. /blog/
site_title: Katalog
url: "/" # the base hostname & protocol for your site
twitter_username: Kt_a_Gilbert
github_username:  ktagilbert
# time: "2015-07-15 19:50:33 -0700"
comments: true
safe: false
paginate: 5
paginate_path: "/page:num/"
markdown: kramdown
include: ["_pages"]
include: ['.htaccess']

# Heroku Config
gems: ['kramdown', 'jekyll-assets', 'octopress-paginate', 'jekyll-paginate']

exclude: ['vendor', 'Procfile', 'Rakefile', 'Gemfile']

custom_redirects:
  - from: https://ktagilbert.github.io/katalog/
    to: http://katalogspace.com/
    type: permanent
